name: Update gist with Twitter data

on:
  schedule:
    - cron: "0 15 * * *"
  push:
    branches: [ master ]
  
jobs:
  update-gist:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: ivgtr/twitter-box@master
        env:
          TZ: Asia/Tokyo
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 21fd0f552ed73091f0b19c4732683805
          TWITTER_ID: mawaru_hana
          TWITTER_TOKEN: ${{ secrets.TWITTER_TOKEN }}
