name: Update gist with Twitter data

on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:

jobs:
  update-gist:
    name: "Update"
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install
        run: npm ci
      - name: Update
        run: |
          npm run workflow
        env:
          TZ: Asia/Tokyo
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 21fd0f552ed73091f0b19c4732683805
          TWITTER_ID: mawaru_hana
          TWITTER_TOKEN: ${{ secrets.TWITTER_TOKEN }}
