name: Update gist with Twitter data

on:
  push: [master]
  
jobs:
  update-gist:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update gist
        runs: |
          yarn
          yarn build
        env:
          TZ: Asia/Tokyo
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 21fd0f552ed73091f0b19c4732683805
          TWITTER_ID: mawaru_hana
          TWITTER_TOKEN: ${{ secrets.TWITTER_TOKEN }}
